### ISSUE TITLE
无法导入Doc2X

### ISSUE THREAD

**Issue by ZhiyaoZhao** [NoEdgeAI/pdfdeal-docs#1]
![image](https://github.com/user-attachments/assets/608a19d7-d90a-4ffb-ad91-7ad6858a13e6)

**Comment by Menghuan1918** [comment]
```bash
pip install -U pdfdeal
```
使用最新版本呢？包的最新版是8月份释放的V0.3.1

![图片](https://github.com/user-attachments/assets/b39e9388-f5a0-4a5b-931f-cb9bcc1a35f6)
